name: Build RP2350 UF2

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Arm GNU Toolchain & CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential cmake ninja-build

      - name: Setup Pico SDK
        run: |
          git clone --depth 1 --branch 2.1.0 https://github.com/raspberrypi/pico-sdk.git
          cd pico-sdk
          git submodule update --init
          echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV

      - name: Build Firmware
        run: |
          mkdir build && cd build
          cmake -DPICO_BOARD=pico2 -DPICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk ..
          make -j$(nproc)

      - name: Upload UF2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sam2695_emulator_uf2
          path: build/*.uf2
